apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000" # Replace with your pod's metrics port
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: Always
          image: kuchedav/{{ .Chart.Name }}:{{ .Chart.Version }}
          ports:
          - containerPort: {{ .Values.port }}
          env:
            - name: DAVID_SECRET
              valueFrom:
                secretKeyRef:
                  name: david-secret
                  key: david_secret
